### ISSUE TITLE
sed not working

### ISSUE THREAD

**Issue by peptoni** [thecamels/zabbix#10]
Hi,

I think this line:
WPlst=$(curl -s $WPurl | egrep "<td>([a-z]+\.){1,7}[a-z]+</td>" | sed -r "s|</?td>||g;/$Exclude/d")
should be 
WPlst=$(curl -s $WPurl | egrep "<td>([a-z]+\.){1,7}[a-z]+</td>" | sed -r "s|</?td>||g;/'$Exclude'/d")
Otherwise is no excluding the excluded blacklists

**Comment by kporembinski** [comment]
Hi,

I have tested this and it is working in both version. Script is mostly from http://giantdorks.org/alain/shell-script-to-query-a-list-of-hostnames-or-ip-addresses-against-a-list-of-local-and-remote-dns-black-lists/
