### ISSUE TITLE
Blacklist command seems to be missing

### ISSUE THREAD

**Issue by psyray** [thecamels/zabbix#17]
Hi,

The blacklist command for the agent seems to be missing.
Error returned is :
![image](https://cloud.githubusercontent.com/assets/1230954/26181324/769c07f2-3b6f-11e7-9f85-e1119586ecc8.png)

**Comment by kporembinski** [comment]
File is here: https://github.com/thecamels/zabbix/blob/master/bin/blacklist.sh
