### ISSUE TITLE
any chance to have XML templates in zabbix 2.2 export format?

### ISSUE THREAD

**Issue by nysander** [thecamels/zabbix#3]
as in the topic ubuntu 14.04 has only zabbix 2.2 and it does not read 3.0 template files, can you export them to 2.2 format and upload?

**Comment by kporembinski** [comment]
You can build Zabbix 3.0 from sources.

We don't have right now Zabbix 2.2.

What Template do you need?

**Comment by nysander** [comment]
opendkim postfix and dovecot, I know that I can build it but i want to use stable and tested packages on this server.

**Comment by nysander** [comment]
I've found deb packages for 3.0 on 14.04 LTS, thanks anyway
