### ISSUE TITLE
mysql php script

### ISSUE THREAD

**Issue by PingLord** [thecamels/zabbix#4]
Hello,
Im having some issues with the php script. It seems it does not work. It writes the file to /tmp but when i run it by hand with --nocache it does not work. All graphs are on No Data.

I tried the following for debugging ( im not a php developer ) : 

added at the start of the script  `try {`

at the end of the script : 
`} catch (Exception $e) {
echo $e->getMessage() . PHP_EOL;
ob_end_flush();
}
`
The error was the following : 
PHP Fatal error:  Call to undefined function debug() in /etc/zabbix/agent-scripts/ss_get_mysql_stats.php on line 125

It seems that it cannot find the functions. If i move the debug function on the first line of the script, it will show errors at the next function parse_cmdline() 

Im running the script on a centos 6 with php 5.6

Have any idea how to solve this or any hints except moving the functions up and down on the file ?

**Comment by kporembinski** [comment]
Can you run for example:

```
# php -qc /etc/zabbix/php.ini /etc/zabbix/bin/ss_get_mysql_stats.php --host localhost --items ok
ok:71579
```

Do you have any results?

**Comment by PingLord** [comment]
Tried that and also found the issue.
There was no result and no output from the script and did not understand why until i went a little deeper into the details.
The issue was with the defined array from php which had different keys from the userparameter provided : 

from php file : 

```
$keys = array(
      'Key_read_requests'           =>  'gg',
      'Key_reads'                   =>  'gh',
      'Key_write_requests'          =>  'gi',
      'Key_writes'                  =>  'gj',
      'history_list'                =>  'gk',
      'innodb_transactions'         =>  'gl',
      'read_views'                  =>  'gm',
      'current_transactions'        =>  'gn',
      'locked_transactions'         =>  'go',
      'active_transactions'         =>  'gp',
      'pool_size'                   =>  'gq',
      'free_pages'                  =>  'gr',
      'database_pages'              =>  'gs',
      'modified_pages'              =>  'gt',
      'pages_read'                  =>  'gu',
      'pages_created'               =>  'gv',
      'pages_written'               =>  'gw',
```

from the userparameter file : 

```
UserParameter=mysql.Key_read_requests,php -qc /etc/zabbix/php.ini /etc/zabbix/bin/ss_get_mysql_stats.php --host localhost --items a0 | awk -F: '{ print $2 }'
UserParameter=mysql.Key_reads,php -qc /etc/zabbix/php.ini /etc/zabbix/bin/ss_get_mysql_stats.php --host localhost --items a1 | awk -F: '{ print $2 }'
UserParameter=mysql.Key_write_requests,php -qc /etc/zabbix/php.ini /etc/zabbix/bin/ss_get_mysql_stats.php --host localhost --items a2 | awk -F: '{ print $2 }'
UserParameter=mysql.Key_writes,php -qc /etc/zabbix/php.ini /etc/zabbix/bin/ss_get_mysql_stats.php --host localhost --items a3 | awk -F: '{ print $2 }'
UserParameter=mysql.history_list,php -qc /etc/zabbix/php.ini /etc/zabbix/bin/ss_get_mysql_stats.php --host localhost --items a4 | awk -F: '{ print $2 }'
UserParameter=mysql.innodb_transactions,php -qc /etc/zabbix/php.ini /etc/zabbix/bin/ss_get_mysql_stats.php --host localhost --items a5 | awk -F: '{ print $2 }'
UserParameter=mysql.read_views,php -qc /etc/zabbix/php.ini /etc/zabbix/bin/ss_get_mysql_stats.php --host localhost --items a6 | awk -F: '{ print $2 }'
```

As you can see, the calls made for the item key in the userparameter is different from the item keys in the php file.

This was it. Hope it helps others also

**Comment by gerardstanczak** [comment]
Hi PingLord,

Thanks for pointing out this issue. I updated the userparameters to the newest version. It seems some of our recent changes were only partially submitted to github, resulting in this inconsistency. If you have time please check the new template and userparameters to see if they are working fine. Thanks!
