### ISSUE TITLE
UserParameters for Postfix

### ISSUE THREAD

**Issue by moondog13** [thecamels/zabbix#7]
This is a lovely set of goodies for Zabbix that I've enjoyed. As I was going through them I was not able to find agent UserParameters for Postfix. The xml template has keys which don't seem to exist in the agent configuration files provided, particularly:

mailqueue-postfix-queue
postfix.version

**Comment by kporembinski** [comment]
Fixed :) Thanks!

https://github.com/thecamels/zabbix/blob/master/zabbix_agentd.conf.d/postfix.conf
